themes:
  test:
    icon: GRASS_BLOCK
    tileSize: 16
    void_y_limit: 10.0
  cave:
    icon: COBBLESTONE
    tileSize: 32
  mineshaft:
    icon: CHEST_MINECART
    tileSize: 48
  library:
    icon: BOOKSHELF
    tileSize: 48
  ruin:
    icon: CHISELED_STONE_BRICKS
    tileSize: 48
  see_of_trees:
    icon: MOSS_BLOCK
    tileSize: 48
  maze:
    icon: COMPASS
    tileSize: 48
